INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(1,'SSC-112','SAPLA');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(2,'SSC-112','BAPPY');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(3,'SSC-112','HABIB');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(4,'SSC-112','ABDUR RAB');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(5,'SSC-112','APU KUMAR');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(6,'SSC-112','ADIBA FERDAUS');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(7,'SSC-112','RASHIDA KHATUN');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(8,'SSC-112','AFSANA AKTER SAUDA');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(9,'SSC-112','RUPA KHATUN');