INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(1,'SSC-12','SAPLA');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(2,'SSC-12','BAPPY');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(3,'SSC-12','HABIB');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(4,'SSC-12','ABDUR RAB');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(5,'SSC-12','APU KUMAR');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(6,'SSC-12','ADIBA FERDAUS');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(7,'SSC-12','RASHIDA KHATUN');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(8,'SSC-12','AFSANA AKTER SAUDA');
INSERT INTO STUDENT (ID ,BATCH ,STUDENT_NAME ) VALUES(9,'SSC-12','RUPA KHATUN');